### ISSUE TITLE
Stylelint ^10.0.0 support

### ISSUE THREAD

**Issue by williammorton** [kristerkari/stylelint-config-recommended-scss#40]
With the latest release of stylelint 10.0.0, a missing peer dependency warning is thrown as only ^8.0.0 || ^9.0.0 are listed as peer dependencies.

**Comment by williammorton** [comment]
> With the latest release of stylelint 10.0.0, a missing peer dependency warning is thrown as only ^8.0.0 || ^9.0.0 are listed as peer dependencies.

Sorry, I just saw that a pull request #39 has already been submitted for this.

**Comment by orionrush** [comment]
If there's something further the community can help with on this - just shout.

**Comment by kristerkari** [comment]
I'll update the peer dependency version range today, for now you can just ignore the warning
